### ISSUE TITLE
:white_check_mark: 결제 페이지 구현

### ISSUE THREAD

**Issue by H-sooyeon** [Step3-kakao-tech-campus/Team17_FE#17]
## Description
- 사용자(견주)가 서비스를 이용한 후 알바생에게 금액을 지불하는 페이지
- 알바생은 산책 완료 후 알바비를 받는 페이지

## To-do
- [x] 해당 공고글에 대한 기본 정보를 확인할 수 있다.
- [x] 서로에 대해 리뷰를 작성할 수 있다.
- [x] 리뷰를 등록할 수 있다.

## ETC
결제 순서가 바뀔 수도 있다.
