### ISSUE TITLE
상세 공고페이지 및 공고글 작성

### ISSUE THREAD

**Issue by YANGSEOKWOO** [Step3-kakao-tech-campus/Team17_FE#19]
## Description
1. 공고의 상세 정보를 보여주는 페이지
2. 공고글 작성하기를 누르면 보여주는 페이지

## To-do
- [x] 공고글 상세페이지 레이아웃 구현
- [x] 공고글 작성 모달창(날짜, 등록한 강아지 선택) 구현
- [x] 등록할 강아지를 선택할 수 있다.
- [x] 희망 일자, 시간을 등록할 수 있다.
- [x] 위치를 등록할 수 있다.
- [x] 지불금액, 특이사항을 작성할 수 있다.
- [x] 공고글을 수정할 수 있다.

## ETC
카카오 map api 사용
