### ISSUE TITLE
:white_check_mark: MSW 연결

### ISSUE THREAD

**Issue by H-sooyeon** [Step3-kakao-tech-campus/Team17_FE#20]
## Description
프론트 목업서버를 구현하여 api를 연결한다.
백엔드 진행도에 맞추기 어려운 사항으로 인해 목업서버를 제작하여 실제 서버와 연결된 것 처럼 동작하도록 한다.

## To-do
이채은
- [x] api 요청 후 전달받을 데이터 json 파일로 만들기
- [x] 맡은 업무에 관한 api handler 함수 만들기

양석우
- [x] api 요청 후 전달받을 데이터 json 파일로 만들기
- [x] 맡은 업무에 관한 api handler 함수 만들기

황수연
- [x] api 요청 후 전달받을 데이터 json 파일로 만들기
- [x] 맡은 업무에 관한 api handler 함수 만들기

## ETC
개발시에 사용하는 목업서버.
프로덕션 모드에선 baseUrl 변경 필요.

**Comment by H-sooyeon** [comment]
각자 체크하면서 프로젝트 진행하시면 됩니다.

**Comment by H-sooyeon** [comment]
@YANGSEOKWOO @H-sooyeon @chaeni1105
