### ISSUE TITLE
:white_check_mark: 로그인 기능 구현

### ISSUE THREAD

**Issue by H-sooyeon** [Step3-kakao-tech-campus/Team17_FE#4]
## Description
사용자로부터 입력받은 이메일과 비밀번호로 로그인을 한다.

## To-do
- [x] 이메일, 비밀번호 상태 관리
- [x] 이메일, 비밀번호 유효성 검사
- [x] 로그인 유지 체크 버튼 추가
- [x] 로그인 UI

**Comment by H-sooyeon** [comment]
api 연결 외 기능 구현 완료
