### ISSUE TITLE
Profile 페이지 구성

### ISSUE THREAD

**Issue by YANGSEOKWOO** [Step3-kakao-tech-campus/Team17_FE#7]
### Description
사용자의 프로필 화면을 구성한다.

#### To-do
- [x] 프로필 UI 
- [x] 본인 프로필 UI
- [x] 상대방 프로필 UI
- [x] 프로필 불러오기 (닉네임, 개밥그릇, 멍코인, 소개글)
- [x] 강아지 프로필  불러오기모달창 UI
- [x] 강아지 프로필  수정하기 모달창 UI
- [x] 본인과 상대방을 구분할 수 있도록

#### ETC
공통 : 산책시키기, 리뷰
본인 : 지원서(본인의)
상대방 : 산책이력
