### ISSUE TITLE
:white_check_mark: 메인 페이지 구현

### ISSUE THREAD

**Issue by H-sooyeon** [Step3-kakao-tech-campus/Team17_FE#9]
## Description
사용자에게 서비스에 관련한 기능을 처음으로 보여주는 페이지이다.

## To-do
- [x] 헤더의 검색창을 통해 제목 검색이 가능하다.
- [x] 헤더의 검색창 안 필터 아이콘을 클릭하여 모달창으로 강아지에 대한 필터처리를 할 수 있다.
- [x] 프로필 이미지로 로그인 상태인지 보여준다.
- [x] 현재 자신의 위치를 보여주며, 위치 텍스트 혹은 아이콘 클릭 시 현재 위치가 재조정 된다.
- [x] 산책 공고글 리스트를 보여준다.
- [x] 무한 스크롤로 공고글을 보여준다.

## ETC
산책 공고글은 자신의 위치와 가까운 순서로 사용자에게 보여주기에 무한스크롤로 적용한다.

**Comment by H-sooyeon** [comment]
api 연결 외 기능 구현 완료
